goserver:
  build: gocd-server
  hostname: go-server
  ports:
    - '8153:8153'

goagent:
  build: gocd-agent
  volumes:
    - /Users/atmaramn/.m2:/root/.m2
  links:
    - goserver
  environment:
    AGENT_KEY: '123456789abcdef'
